import { FeedPost } from "./pageType";

export const dummyPost: FeedPost[] = [
  {
    "postId": 101,
    "userId": 1,
    "userName": "BaliDreamer",
    "displayName": "Made Wira",
    "userAvatar": "https://i.pravatar.cc/150?u=1",
    "imageUrl": "https://picsum.photos/id/10/500/500",
    "caption": "Chasing sunsets in Bali. The colors tonight were absolutely breathtaking, painting the sky in shades of deep orange and violet. I could sit here for hours just watching the horizon change as the light fades away. It’s the perfect way to end a busy day and find a moment of peace. There is truly nowhere else I'd rather be right now. I’m already looking forward to doing this all again tomorrow.",
    "postDate": "2026-03-06T13:49:02Z",
    "likeCount": 124,
    "commentCount": 12,
    "shareCount": 5,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 102,
    "userId": 2,
    "userName": "TechInnovator",
    "displayName": "Sarah Jenkins",
    "userAvatar": "https://i.pravatar.cc/150?u=2",
    "imageUrl": "https://picsum.photos/id/11/500/500",
    "caption": "The future of AI is here, and it is moving faster than I ever anticipated. Every single day brings a new, massive breakthrough that completely changes the current tech landscape. It is truly an exciting time to be working in this field, and I feel lucky to be a part of it. I can't wait to see what comes next, even though it is a bit overwhelming at times. We are really just scratching the surface of what is possible with these models.",
    "postDate": "2026-03-06T09:30:00Z",
    "likeCount": 890,
    "commentCount": 45,
    "shareCount": 120,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 103,
    "userId": 3,
    "userName": "BrunchLover",
    "displayName": "Mark Thompson",
    "userAvatar": "https://i.pravatar.cc/150?u=3",
    "imageUrl": "https://picsum.photos/id/12/500/500",
    "caption": "Best brunch ever! The eggs benedict were cooked to absolute perfection. I’m already planning my next visit because the coffee was just as good as the food. Seriously, you have to try this spot if you’re in town this weekend. The atmosphere is cozy, the service is fast, and everything on the menu looks incredible. It was exactly the start to the day that I needed.",
    "postDate": "2026-03-05T10:15:00Z",
    "likeCount": 45,
    "commentCount": 3,
    "shareCount": 1,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 104,
    "userId": 4,
    "userName": "CityNightOwl",
    "displayName": "Elena Rodriguez",
    "userAvatar": "https://i.pravatar.cc/150?u=4",
    "imageUrl": "https://picsum.photos/id/13/500/500",
    "caption": "Lost in the concrete jungle. Mesmerizing city streets at night always make me feel so alive and connected to the world. There is a specific kind of energy you only find after dark when the lights come on. I wouldn't trade these views for anything else. Exploring the urban landscape is my favorite way to spend an evening. I feel like I discover something new every single time I walk these blocks.",
    "postDate": "2026-03-04T22:45:00Z",
    "likeCount": 230,
    "commentCount": 18,
    "shareCount": 8,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 105,
    "userId": 5,
    "userName": "FitnessFiend",
    "displayName": "Jake Miller",
    "userAvatar": "https://i.pravatar.cc/150?u=5",
    "imageUrl": "https://picsum.photos/id/14/500/500",
    "caption": "No pain, no gain. Today's workout was incredibly intense, but I finished every set as planned. I really pushed my limits during the final round, and it feels great to be done. Now, it's time for some well-deserved recovery and a massive protein shake. Consistency is the only way to get real results over the long term. I'm already hyped for the next training session tomorrow.",
    "postDate": "2026-03-02T08:00:00Z",
    "likeCount": 560,
    "commentCount": 32,
    "shareCount": 22,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 106,
    "userId": 6,
    "userName": "MinimalistMind",
    "displayName": "Chloe Zhang",
    "userAvatar": "https://i.pravatar.cc/150?u=6",
    "imageUrl": "https://picsum.photos/id/15/500/500",
    "caption": "Less is truly more. Decluttering my space and my mind has been a total game changer for my daily routine. I feel so much lighter and more focused now that I've stripped away the unnecessary stuff. It’s amazing what happens when you finally let go of the excess. I highly recommend trying this if you feel overwhelmed. My home feels like a sanctuary again.",
    "postDate": "2026-02-27T14:20:00Z",
    "likeCount": 102,
    "commentCount": 5,
    "shareCount": 2,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 107,
    "userId": 7,
    "userName": "WanderlustSoul",
    "displayName": "David O'Connell",
    "userAvatar": "https://i.pravatar.cc/150?u=7",
    "imageUrl": "https://picsum.photos/id/16/500/500",
    "caption": "Another plane ticket booked for next month. Can't stay in one place for too long because the world is just too big to explore. I'm already counting down the days until my next takeoff. Every new destination teaches me something about myself that I didn't know before. I live for these adventures and the stories I get to bring back home. Can't wait for this next chapter.",
    "postDate": "2026-02-20T11:00:00Z",
    "likeCount": 340,
    "commentCount": 22,
    "shareCount": 45,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 108,
    "userId": 8,
    "userName": "CoffeeAddict",
    "displayName": "Amelia White",
    "userAvatar": "https://i.pravatar.cc/150?u=8",
    "imageUrl": "https://picsum.photos/id/17/500/500",
    "caption": "First things first: coffee. My morning ritual is the only thing keeping me sane before I start the day. One cup is simply never enough to get me moving. It’s the perfect start to a busy day and helps me organize my thoughts. I don't think I could function without this caffeine boost. Seriously, don't talk to me until I've had my brew.",
    "postDate": "2026-02-13T07:30:00Z",
    "likeCount": 88,
    "commentCount": 10,
    "shareCount": 4,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 109,
    "userId": 9,
    "userName": "ArtisticVibes",
    "displayName": "Leo Dubois",
    "userAvatar": "https://i.pravatar.cc/150?u=9",
    "imageUrl": "https://picsum.photos/id/18/500/500",
    "caption": "My latest canvas is finally complete. I am proud of how it turned out, especially the color blending in the foreground. Art is such a great outlet for my emotions when words aren't enough. I’m excited to start the next project already and see where my imagination takes me. Painting always makes me feel so fulfilled. Let me know what you think of this piece.",
    "postDate": "2026-02-06T16:00:00Z",
    "likeCount": 670,
    "commentCount": 55,
    "shareCount": 33,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 110,
    "userId": 10,
    "userName": "PetLoverExtraordinaire",
    "displayName": "Sophie Kim",
    "userAvatar": "https://i.pravatar.cc/150?u=10",
    "imageUrl": "https://picsum.photos/id/19/500/500",
    "caption": "Just look at this adorable face. Having a furry friend is the best feeling in the world, no matter how bad the day has been. They bring so much joy to every single day with their unconditional love. I couldn't imagine my life without them by my side. They really are the best companions you could ask for. My heart just melts every time I see this smile.",
    "postDate": "2026-01-30T10:00:00Z",
    "likeCount": 1200,
    "commentCount": 150,
    "shareCount": 300,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 111,
    "userId": 11,
    "userName": "GamerLife",
    "displayName": "Alex Rivera",
    "userAvatar": "https://i.pravatar.cc/150?u=11",
    "imageUrl": "https://picsum.photos/id/20/500/500",
    "caption": "Updated my gaming setup. New lights and keyboard make a huge difference in my daily performance. It finally feels like a real battle station now. Time to test it out with some intense matches against the squad. The aesthetic is perfect for late night sessions. I am incredibly happy with how this build turned out. Time to climb the ranks.",
    "postDate": "2026-01-23T23:00:00Z",
    "likeCount": 450,
    "commentCount": 67,
    "shareCount": 12,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 112,
    "userId": 12,
    "userName": "BookishSoul",
    "displayName": "Hannah Scott",
    "userAvatar": "https://i.pravatar.cc/150?u=12",
    "imageUrl": "https://picsum.photos/id/21/500/500",
    "caption": "Lost in a good story. Nothing like a book on a rainy afternoon to help me escape reality for a while. It’s the perfect way to recharge my batteries after a long week. I might just stay here and read all day long. Getting buried in a book is my favorite hobby. You really do live a thousand lives when you read.",
    "postDate": "2026-01-16T15:00:00Z",
    "likeCount": 95,
    "commentCount": 8,
    "shareCount": 3,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 113,
    "userId": 13,
    "userName": "ChefAtHome",
    "displayName": "Gordon Ramsey Jr",
    "userAvatar": "https://i.pravatar.cc/150?u=13",
    "imageUrl": "https://picsum.photos/id/22/500/500",
    "caption": "Sharing my secret family recipe today. Enjoy, and please let me know how it turns out in the comments. Cooking is all about love, patience, and good technique. I’m happy to finally pass this one down to all of you. It’s a classic dish that never gets old. Don't be afraid to experiment with the flavors.",
    "postDate": "2026-01-09T12:00:00Z",
    "likeCount": 320,
    "commentCount": 40,
    "shareCount": 90,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 114,
    "userId": 14,
    "userName": "YogaJourney",
    "displayName": "Maya Patel",
    "userAvatar": "https://i.pravatar.cc/150?u=14",
    "imageUrl": "https://picsum.photos/id/23/500/500",
    "caption": "Find your balance and breathe deep. Morning yoga is essential for my mental clarity and overall health. It sets the tone for everything else I do today. I feel so refreshed, centered, and ready to take on the world. Even on the busiest days, I try to make time for this. It really is a game changer for me.",
    "postDate": "2026-01-02T06:30:00Z",
    "likeCount": 210,
    "commentCount": 15,
    "shareCount": 7,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 115,
    "userId": 15,
    "userName": "HistoryBuff",
    "displayName": "Dr. Arthur Vance",
    "userAvatar": "https://i.pravatar.cc/150?u=15",
    "imageUrl": "https://picsum.photos/id/24/500/500",
    "caption": "Exploring ancient ruins. History truly comes alive here in ways books simply cannot describe. Walking through these sites is a humbling, incredible experience. I learn something new every single time I visit. It's important to remember where we came from. I am so lucky to be able to see this in person. Hopefully, we can preserve this for future generations.",
    "postDate": "2025-12-25T10:00:00Z",
    "likeCount": 155,
    "commentCount": 12,
    "shareCount": 20,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 116,
    "userId": 16,
    "userName": "CodeWrangler",
    "displayName": "Benny Coder",
    "userAvatar": "https://i.pravatar.cc/150?u=16",
    "imageUrl": "https://picsum.photos/id/25/500/500",
    "caption": "It works on my machine, which is always a small victory in my book. Debugging legacy code is incredibly hard, but someone has to do it. Slowly but surely, I am making progress. One bug at a time is the motto for today. Hopefully, the build succeeds on the server as well. I'm crossing my fingers that this fix actually works.",
    "postDate": "2025-12-18T18:00:00Z",
    "likeCount": 400,
    "commentCount": 80,
    "shareCount": 40,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 117,
    "userId": 17,
    "userName": "VintageVibe",
    "displayName": "Jasmine Lee",
    "userAvatar": "https://i.pravatar.cc/150?u=17",
    "imageUrl": "https://picsum.photos/id/26/500/500",
    "caption": "Channeling OOTD vibes. Mixing vintage with modern is my favorite style because it keeps things interesting. You should always wear what makes you feel like yourself. Finding these unique pieces is such a treasure hunt. I'm really happy with how this look came together today. It feels like the perfect blend of old and new.",
    "postDate": "2025-12-11T09:00:00Z",
    "likeCount": 990,
    "commentCount": 200,
    "shareCount": 50,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 118,
    "userId": 18,
    "userName": "HikingAdventures",
    "displayName": "Tom Walker",
    "userAvatar": "https://i.pravatar.cc/150?u=18",
    "imageUrl": "https://picsum.photos/id/27/500/500",
    "caption": "Fresh air, quiet hike. Exactly what I needed after a long week of work. Being out in nature resets everything for me. I’m ready for whatever comes next, feeling totally refreshed. The views from the trail were spectacular today. I'm glad I decided to head out early this morning. It was definitely worth the effort to get here.",
    "postDate": "2025-12-04T14:00:00Z",
    "likeCount": 75,
    "commentCount": 4,
    "shareCount": 2,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 119,
    "userId": 19,
    "userName": "VinylCollector",
    "displayName": "Sam Record",
    "userAvatar": "https://i.pravatar.cc/150?u=19",
    "imageUrl": "https://picsum.photos/id/28/500/500",
    "caption": "Vinyl collection growing. The warmth of a record player is special and truly irreplaceable. It’s all about the experience of the music for me. I love finding hidden gems like this at the local shop. It makes every listening session unique. This record has been on my list for ages. I’m really enjoying it right now.",
    "postDate": "2025-11-27T20:00:00Z",
    "likeCount": 280,
    "commentCount": 30,
    "shareCount": 15,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 120,
    "userId": 20,
    "userName": "CozyCorners",
    "displayName": "Mia Comfort",
    "userAvatar": "https://i.pravatar.cc/150?u=20",
    "imageUrl": "https://picsum.photos/id/29/500/500",
    "caption": "Cozy corner goals achieved. I'm ready for reading and relaxing for the rest of the day. It’s the ultimate weekend vibe. I don't think I'm moving from here for a while. It feels so nice to have a dedicated spot for peace and quiet. Everything is just right. Time to dive into a new chapter.",
    "postDate": "2025-11-20T11:00:00Z",
    "likeCount": 510,
    "commentCount": 60,
    "shareCount": 95,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 121,
    "userId": 21,
    "userName": "GoldenHourGal",
    "displayName": "Lily Sunshine",
    "userAvatar": "https://i.pravatar.cc/150?u=21",
    "imageUrl": "https://picsum.photos/id/30/500/500",
    "caption": "Golden hour shots are the best. They are so magical, warm, and inviting. The light really transforms everything it touches in the best way possible. I wish this specific time of day lasted all afternoon long. It's my favorite time to take photos. Every shot looks like a dream. Can't wait to edit these.",
    "postDate": "2025-11-13T17:30:00Z",
    "likeCount": 800,
    "commentCount": 90,
    "shareCount": 45,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 122,
    "userId": 22,
    "userName": "ScienceGeek",
    "displayName": "Dr. Ben Science",
    "userAvatar": "https://i.pravatar.cc/150?u=22",
    "imageUrl": "https://picsum.photos/id/31/500/500",
    "caption": "Science is wild. Sharing these little facts makes me realize how little we actually know about the universe. There is always more to discover, no matter how much we study. I hope you find this as interesting as I do. It’s fascinating stuff to think about. Let me know if you want more science facts like this one.",
    "postDate": "2025-11-06T10:00:00Z",
    "likeCount": 130,
    "commentCount": 20,
    "shareCount": 50,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 123,
    "userId": 23,
    "userName": "PeakSeeker",
    "displayName": "Clara Mountain",
    "userAvatar": "https://i.pravatar.cc/150?u=23",
    "imageUrl": "https://picsum.photos/id/32/500/500",
    "caption": "View from the top is worth the pain. My legs are tired, but my spirit is soaring after this climb. It's a reminder of why I climb in the first place. Absolutely stunning views. I feel so small up here in the best way possible. This is what I live for. Can't wait to plan the next summit.",
    "postDate": "2025-10-30T09:00:00Z",
    "likeCount": 600,
    "commentCount": 45,
    "shareCount": 80,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 124,
    "userId": 24,
    "userName": "MovieBuff",
    "displayName": "Oscar Watcher",
    "userAvatar": "https://i.pravatar.cc/150?u=24",
    "imageUrl": "https://picsum.photos/id/33/500/500",
    "caption": "Weekend binge list is ready. Time to relax and catch up on some cinema classics. I’ve been waiting all week for this. No interruptions allowed, just me and the screen. It's going to be a great marathon of films. I've got my popcorn ready. Let me know what you're watching this weekend.",
    "postDate": "2025-10-23T20:00:00Z",
    "likeCount": 220,
    "commentCount": 35,
    "shareCount": 10,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 125,
    "userId": 25,
    "userName": "TrickMaster",
    "displayName": "Skate Kid",
    "userAvatar": "https://i.pravatar.cc/150?u=25",
    "imageUrl": "https://picsum.photos/id/34/500/500",
    "caption": "Learning a new trick is humbling, but I am getting closer every day. It’s just about repetition and persistence until it clicks. I’ll land it soon, I promise. It takes so many tries, but it’s so rewarding when you finally get it right. I love the process of improving. Skating is my life.",
    "postDate": "2025-10-16T15:00:00Z",
    "likeCount": 180,
    "commentCount": 14,
    "shareCount": 5,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 126,
    "userId": 26,
    "userName": "PlantParent",
    "displayName": "Ivy Green",
    "userAvatar": "https://i.pravatar.cc/150?u=26",
    "imageUrl": "https://picsum.photos/id/35/500/500",
    "caption": "Indoor jungle is out of control, but I'm loving it. Everything is growing so well this season. It really makes the house feel like a home. Time for some pruning and maintenance. I'm thinking of adding a few more varieties soon. It's such a relaxing hobby to have. They really add so much life to the room.",
    "postDate": "2025-10-09T10:00:00Z",
    "likeCount": 350,
    "commentCount": 25,
    "shareCount": 12,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 127,
    "userId": 27,
    "userName": "CarEnthusiast",
    "displayName": "Auto Mike",
    "userAvatar": "https://i.pravatar.cc/150?u=27",
    "imageUrl": "https://picsum.photos/id/36/500/500",
    "caption": "Nothing like a clean ride on a sunny day. It’s the little things that make me happy. Can’t wait to take this beauty out for a spin later. I put in a lot of work to keep her looking this good. There's nothing like a drive on an open road. It's pure therapy for me.",
    "postDate": "2025-10-02T13:00:00Z",
    "likeCount": 420,
    "commentCount": 50,
    "shareCount": 30,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 128,
    "userId": 28,
    "userName": "DIYMaster",
    "displayName": "FixIt Felix",
    "userAvatar": "https://i.pravatar.cc/150?u=28",
    "imageUrl": "https://picsum.photos/id/37/500/500",
    "caption": "Restored an old chair. Giving furniture second chances feels so rewarding. It’s way better than throwing things away when they still have life left in them. I think it looks great now in the new spot. It was a lot of sanding, but worth it. I love these types of projects. Keeps me busy and productive.",
    "postDate": "2025-09-25T11:00:00Z",
    "likeCount": 290,
    "commentCount": 38,
    "shareCount": 18,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 129,
    "userId": 29,
    "userName": "CryptoKing",
    "displayName": "Moon Boy",
    "userAvatar": "https://i.pravatar.cc/150?u=29",
    "imageUrl": "https://picsum.photos/id/38/500/500",
    "caption": "To the moon! Volatility is high, but I'm holding strong regardless. I believe in the long-term vision of this project. This is just the beginning of the cycle. I am not selling anytime soon. It's a bumpy ride, but worth it in the end. Let's see what happens.",
    "postDate": "2025-09-18T09:00:00Z",
    "likeCount": 550,
    "commentCount": 100,
    "shareCount": 200,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 130,
    "userId": 30,
    "userName": "SoloTraveler",
    "displayName": "Wanderlust Jill",
    "userAvatar": "https://i.pravatar.cc/150?u=30",
    "imageUrl": "https://picsum.photos/id/39/500/500",
    "caption": "Exploring solo. Freedom is great and I wouldn't trade it for anything else. You learn so much about yourself when you're on your own in a new place. It's truly empowering. I love the flexibility of doing whatever I want. Can't wait to see what else I discover. Solo travel really opens your eyes.",
    "postDate": "2025-09-11T14:00:00Z",
    "likeCount": 310,
    "commentCount": 28,
    "shareCount": 15,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 131,
    "userId": 31,
    "userName": "LondonFashion",
    "displayName": "Style Brit",
    "userAvatar": "https://i.pravatar.cc/150?u=31",
    "imageUrl": "https://picsum.photos/id/40/500/500",
    "caption": "London fashion inspiration everywhere. You see something new on every single corner. It’s such an eclectic city to live in. I'm constantly taking notes for my own wardrobe. I love how everyone is so expressive here. You can really be yourself. Can't wait to go shopping later.",
    "postDate": "2025-09-04T12:00:00Z",
    "likeCount": 480,
    "commentCount": 40,
    "shareCount": 25,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 132,
    "userId": 32,
    "userName": "ProudTeacher",
    "displayName": "Mr. Ed",
    "userAvatar": "https://i.pravatar.cc/150?u=32",
    "imageUrl": "https://picsum.photos/id/41/500/500",
    "caption": "Proud of my students for finishing their projects. They worked so hard all semester long. Seeing them succeed makes it all worth it for me. I couldn't be happier with how they turned out. They really stepped up to the challenge. Teaching is such a rewarding job. I love watching them grow.",
    "postDate": "2025-08-28T16:00:00Z",
    "likeCount": 600,
    "commentCount": 80,
    "shareCount": 5,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 133,
    "userId": 33,
    "userName": "HealthNut",
    "displayName": "Kale King",
    "userAvatar": "https://i.pravatar.cc/150?u=33",
    "imageUrl": "https://picsum.photos/id/42/500/500",
    "caption": "Superfood bowl. Healthy is not boring if you know how to season it right. I feel so much better when I eat like this every day. It's delicious and simple to make. My body really appreciates the nutrient-dense meals. This is definitely going into my weekly rotation. What do you put in your bowls?",
    "postDate": "2025-08-21T10:00:00Z",
    "likeCount": 200,
    "commentCount": 15,
    "shareCount": 6,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 134,
    "userId": 34,
    "userName": "MusicMaker",
    "displayName": "Beat Drop",
    "userAvatar": "https://i.pravatar.cc/150?u=34",
    "imageUrl": "https://picsum.photos/id/43/500/500",
    "caption": "Practice makes perfect. Music is fuel for my soul. I'm trying to experiment with some new sounds this week in the studio. It’s challenging, but really fun to find a new groove. I hope I can share the final track soon. Music connects us all. Keep listening and keep creating.",
    "postDate": "2025-08-14T09:00:00Z",
    "likeCount": 750,
    "commentCount": 60,
    "shareCount": 40,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 135,
    "userId": 35,
    "userName": "WriterLife",
    "displayName": "Pen Push",
    "userAvatar": "https://i.pravatar.cc/150?u=35",
    "imageUrl": "https://picsum.photos/id/44/500/500",
    "caption": "Coffee and words are pillars of existence for me. They keep me going through the long hours of writing. Sometimes I just need to get it all on paper to feel sane. Writing is such a relief and an outlet. I am finally making progress on my latest manuscript. Stay tuned for updates.",
    "postDate": "2025-08-07T11:00:00Z",
    "likeCount": 110,
    "commentCount": 9,
    "shareCount": 2,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 136,
    "userId": 36,
    "userName": "DogGroomer",
    "displayName": "Pup Stylist",
    "userAvatar": "https://i.pravatar.cc/150?u=36",
    "imageUrl": "https://picsum.photos/id/45/500/500",
    "caption": "Before and after. Love my furry clients and seeing them happy when they leave. It’s such a satisfying job. Who knew grooming could be this cute? I really enjoy the creative part of styling them. They are so well-behaved today. Can't wait for the next appointment. Such a great day at the salon.",
    "postDate": "2025-07-31T15:00:00Z",
    "likeCount": 900,
    "commentCount": 120,
    "shareCount": 50,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 137,
    "userId": 37,
    "userName": "Stargazer",
    "displayName": "Starry Eyes",
    "userAvatar": "https://i.pravatar.cc/150?u=37",
    "imageUrl": "https://picsum.photos/id/46/500/500",
    "caption": "Clear view of the stars. Mind blowing how vast the universe is. It really makes you feel small and connected. I love nights like this when the sky is clear. I could spend all night looking up. There is something so peaceful about the silence. It is truly a beautiful sight to behold.",
    "postDate": "2025-07-24T22:00:00Z",
    "likeCount": 320,
    "commentCount": 22,
    "shareCount": 15,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 138,
    "userId": 38,
    "userName": "ArchLover",
    "displayName": "Building Buff",
    "userAvatar": "https://i.pravatar.cc/150?u=38",
    "imageUrl": "https://picsum.photos/id/47/500/500",
    "caption": "Lines and light. Architecture is art in its own form, and I love capturing the symmetry of the buildings. Every angle tells a unique story. It is amazing how much thought goes into these designs. I appreciate the craft so much. I will definitely be back to shoot this location again at sunrise.",
    "postDate": "2025-07-17T13:00:00Z",
    "likeCount": 240,
    "commentCount": 18,
    "shareCount": 8,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 139,
    "userId": 39,
    "userName": "SurfingLife",
    "displayName": "Wave Rider",
    "userAvatar": "https://i.pravatar.cc/150?u=39",
    "imageUrl": "https://picsum.photos/id/48/500/500",
    "caption": "Catching waves. Nothing beats this feeling of being on the water. It’s pure, unadulterated freedom. Can’t wait for the next big swell to roll in. I love the ocean and everything it offers. It’s a great way to start my day. I feel so invigorated afterwards. See you out there.",
    "postDate": "2025-07-10T08:00:00Z",
    "likeCount": 530,
    "commentCount": 45,
    "shareCount": 25,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 140,
    "userId": 40,
    "userName": "LogoDesign",
    "displayName": "Graphic Guy",
    "userAvatar": "https://i.pravatar.cc/150?u=40",
    "imageUrl": "https://picsum.photos/id/49/500/500",
    "caption": "Logo study in progress. Getting closer to the final version. It's all about balance, color, and simplicity in design. I think this one has real potential for the client. I'm really digging the font choices. Can't wait to present these concepts. Hopefully, they like the direction. Design is a constant iteration.",
    "postDate": "2025-07-03T16:00:00Z",
    "likeCount": 270,
    "commentCount": 30,
    "shareCount": 12,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 141,
    "userId": 41,
    "userName": "ParentingLife",
    "displayName": "Mom Life",
    "userAvatar": "https://i.pravatar.cc/150?u=41",
    "imageUrl": "https://picsum.photos/id/50/500/500",
    "caption": "Chaos and love. Worth every single moment of it. Even when it’s loud and messy, I wouldn’t trade it for anything. It's the most challenging and rewarding role I’ve ever had in my life. I love seeing the world through their eyes. It's a fun ride that never ends. Parenthood is a wild adventure.",
    "postDate": "2025-06-26T11:00:00Z",
    "likeCount": 650,
    "commentCount": 95,
    "shareCount": 10,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 142,
    "userId": 42,
    "userName": "DadJokes",
    "displayName": "Pun Master",
    "userAvatar": "https://i.pravatar.cc/150?u=42",
    "imageUrl": "https://picsum.photos/id/51/500/500",
    "caption": "Best dad joke of the year. Get ready because I have a ton of these in my back pocket. Hope you're ready for some major eye-rolls. Let the puns begin! Life is too short to be serious all the time. Laughter really is the best medicine for everyone.",
    "postDate": "2025-06-19T09:00:00Z",
    "likeCount": 440,
    "commentCount": 70,
    "shareCount": 60,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 143,
    "userId": 43,
    "userName": "MeditationMind",
    "displayName": "Zen Master",
    "userAvatar": "https://i.pravatar.cc/150?u=43",
    "imageUrl": "https://picsum.photos/id/52/500/500",
    "caption": "Find your center. Daily noise reduction is essential for me. Taking a moment to breathe deeply makes a huge difference in my stress levels. I feel so much more balanced now that I have a routine. Peace of mind is the greatest gift. Don't forget to take care of yourself today.",
    "postDate": "2025-06-12T07:00:00Z",
    "likeCount": 190,
    "commentCount": 12,
    "shareCount": 9,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 144,
    "userId": 44,
    "userName": "EventPlanner",
    "displayName": "Party Planner",
    "userAvatar": "https://i.pravatar.cc/150?u=44",
    "imageUrl": "https://picsum.photos/id/53/500/500",
    "caption": "Wedding setup finished. Planning is complete, now let's party. It’s always satisfying to see everything come together perfectly after weeks of work. Hope the guests enjoy the night as much as I enjoyed planning it. It's going to be a memorable evening for sure. The venue looks absolutely stunning tonight.",
    "postDate": "2025-06-05T14:00:00Z",
    "likeCount": 380,
    "commentCount": 50,
    "shareCount": 20,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 145,
    "userId": 45,
    "userName": "TechLaunch",
    "displayName": "Tech Hype",
    "userAvatar": "https://i.pravatar.cc/150?u=45",
    "imageUrl": "https://picsum.photos/id/54/500/500",
    "caption": "Big release today. The hype is real and I’m buzzing. We’ve worked so hard for this moment, and it feels great to finally share it. Can't wait to hear the feedback from all of you. It's been an incredible journey. Thanks for being along for the ride. Let's see what people think.",
    "postDate": "2025-05-29T10:00:00Z",
    "likeCount": 1500,
    "commentCount": 300,
    "shareCount": 800,
    "isSaved": false,
    "isLiked": true
  },
  {
    "postId": 146,
    "userId": 46,
    "userName": "HomeDecor",
    "displayName": "Dresser Fix",
    "userAvatar": "https://i.pravatar.cc/150?u=46",
    "imageUrl": "https://picsum.photos/id/55/500/500",
    "caption": "Painted the dresser. Perfect weekend project that was way overdue. It looks like brand new furniture now that the fresh coat is dry. I'm really proud of this quick update. Small changes make a big difference in a room. Love how the color pops. Onto the next project.",
    "postDate": "2025-05-22T13:00:00Z",
    "likeCount": 210,
    "commentCount": 25,
    "shareCount": 7,
    "isSaved": true,
    "isLiked": false
  },
  {
    "postId": 147,
    "userId": 47,
    "userName": "TrailRunner",
    "displayName": "Squad Goal",
    "userAvatar": "https://i.pravatar.cc/150?u=47",
    "imageUrl": "https://picsum.photos/id/56/500/500",
    "caption": "Trail day with the squad. Stunning scenery made the hard run worth it for everyone involved. We are already planning the next one for next weekend. Who's in for the next challenge? Running with friends is so much better. I loved the energy on the trails. It was a great day.",
    "postDate": "2025-05-15T09:00:00Z",
    "likeCount": 460,
    "commentCount": 40,
    "shareCount": 22,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 148,
    "userId": 48,
    "userName": "StudioVibes",
    "displayName": "Late Night Beat",
    "userAvatar": "https://i.pravatar.cc/150?u=48",
    "imageUrl": "https://picsum.photos/id/57/500/500",
    "caption": "Late night session. Feeling right about these sounds I’m working on. Sometimes the best ideas come when it’s quiet and everyone else is asleep. I think I’ve got something good here. Can't wait to finish the mix later. Music is such a creative escape. It’s going to be a solid track.",
    "postDate": "2025-05-08T23:00:00Z",
    "likeCount": 330,
    "commentCount": 28,
    "shareCount": 15,
    "isSaved": false,
    "isLiked": false
  },
  {
    "postId": 149,
    "userId": 49,
    "userName": "CafeOwner",
    "displayName": "Brew Master",
    "userAvatar": "https://i.pravatar.cc/150?u=49",
    "imageUrl": "https://picsum.photos/id/58/500/500",
    "caption": "Open for business! Morning brew is ready for everyone. Come by and say hello. We have the best coffee in town. Nothing beats a fresh cup. I love serving my regulars. It’s going to be a busy and productive day. See you all soon. Have a great morning.",
    "postDate": "2025-05-01T07:00:00Z",
    "likeCount": 120,
    "commentCount": 10,
    "shareCount": 3,
    "isSaved": true,
    "isLiked": true
  },
  {
    "postId": 150,
    "userId": 50,
    "userName": "FarewellPost",
    "displayName": "Goodbye Feed",
    "userAvatar": "https://i.pravatar.cc/150?u=50",
    "imageUrl": "https://picsum.photos/id/59/500/500",
    "caption": "That's a wrap. Thanks for the journey and all the support along the way. I've learned so much and had a great time connecting with everyone here. See you all on the next big adventure. Thank you for being a part of this story. It’s time for a new chapter. Farewell and good luck.",
    "postDate": "2024-03-06T13:54:02Z",
    "likeCount": 99,
    "commentCount": 5,
    "shareCount": 2,
    "isSaved": true,
    "isLiked": false
  }
];