export { default as logoCompany } from './logo-company.svg'
export { default as gradientBg } from './gradient-bg.png'
export { default as iconEye } from './icon-eye.svg'
export { default as iconEyeOff } from './icon-eye-off.svg'
export { default as icMenu } from './ic-menu.svg'
export { default as icClose } from './ic-close.svg'
export { default as icSearch } from './ic-search.svg'
export { default as icClearSearch } from './ic-clear-search.svg'
export { default as imgProfileTemp } from './img-profile-temp.svg'
export { default as icLogout } from './ic-logout.svg'
export { default as imageFeed } from './image-feed.svg'

export { default as iconLike0 } from './icon-like-0.svg'
export { default as iconLike1 } from './icon-like-1.svg'
export { default as iconSave0 } from './icon-save-0.svg'
export { default as iconSave1 } from './icon-save-1.svg'
export { default as iconComment } from './icon-comment.svg'
export { default as iconShare } from './icon-share.svg'

export { default as iconHome0 } from './icon-home-0.svg'
export { default as iconHome1 } from './icon-home-1.svg'
export { default as iconProfile0 } from './icon-profile-0.svg'
export { default as iconProfile1 } from './icon-profile-1.svg'
export { default as iconAdd } from './icon-add.svg'

export { default as icCheckCircle } from './ic-check-circle.svg'

export { default as icSocial1Fb } from './ic-social-1-fb.svg'
export { default as icSocial2Ig } from './ic-social-2-ig.svg'
export { default as icSocial3Linkedin } from './ic-social-3-linkedin.svg'
export { default as icSocial4Tiktok } from './ic-social-4-tiktok.svg'