export { default as logoCompany } from './logo-company.svg'
export { default as gradientBg } from './gradient-bg.png'
export { default as iconEye } from './icon-eye.svg'
export { default as iconEyeOff } from './icon-eye-off.svg'
export { default as icMenu } from './ic-menu.svg'
export { default as icClose } from './ic-close.svg'
export { default as icSearch } from './ic-search.svg'
export { default as imgProfileTemp } from './img-profile-temp.svg'